### ISSUE TITLE
Request: clarify what information is stored to snyk with `snyk monitor` 

### ISSUE THREAD

**Issue by harriha** [snyk/docs#7]
Hi,

I guess it is safe to assume that when starting to monitor a project with `snyk monitor`, it's only the `package.json` content which is pulled to snyk servers for monitoring. However, would be great to see this clarified in the docs explicitly (and/or also to be able to observe this data from my project page).

**Comment by johannakoll** [comment]
Hello, 

This is covered in our Terms of Service, in Section 9 - "Project Data and Rights you give us" - and can be found here: https://snyk.io/policies

The Terms of Service has more detail that is worth reading, but to answer your question about what data we access, here is the relevant paragraph: 

"This information includes, but is not limited to, information relating to the project (such as the project name and metadata), information relating to the dependencies, including open source and closed source but locally available to our tool, being used and how they are referenced by the project, Snyk-related files and environmental information (“Project Information”). We may also collect Project Information for each of the project’s dependencies (“Dependency Information”)."

Does this clarify it?

**Comment by harriha** [comment]
Hi,

Thanks, didn't realize to check the Terms of Service. Its content clarifies things indeed, although if I'd be very worried about the source code of my private repository, the ToS content might not be quite enough to convince me (I see "usual" parts such as the "[..] but is not limited to" etc). 

But in any case, the potential risk is the same in all similar services, so in the case of a developer extremely cautious about the project sources, all similar cloud-style services would be out of the question.  Thus, all in all, all good here, thanks for the response, don't mean to go into hair-splitting mood here. A potential practical thing to keep this part more transparent would be to have all data related to a project visible/downloadable from your service.
